Repository snulion11th-seminar/react, pull requests merged in 2023-05, with the labels that each got.

#32 9주차 과제완료
  src/components/comment/CommentElement.jsx
  src/components/comment/index.jsx
  src/data/comments.js
  src/routes/PostDetailPage.jsx
Labels: hw

#45 이희선 9주차 과제 제출
  src/components/Comment/CommentElement.jsx
  src/components/Comment/index.jsx
  src/data/comment.js
  src/routes/PostDetailPage.jsx
Labels: LGTM

#40 eojin w9 assignment
  src/components/Comment/CommentElement.jsx
  src/components/Comment/index.jsx
  src/components/Form/index.jsx
  src/components/Posts/index.jsx
  src/data/comments.js
  src/routes/PostCreatePage.jsx
  src/routes/PostDetailPage.jsx
  src/routes/PostEditPage.jsx
  src/routes/SignInPage.jsx
  src/routes/SignUpPage.jsx
Labels: wontfix

#47 [feat] comment feature updated; 9th week assignment
  src/components/Comment/CommentElement.jsx
  src/components/Comment/index.jsx
  src/components/Posts/index.jsx
  src/data/comments.js
  src/routes/PostDetailPage.jsx
Labels: wontfix

#33 feat. 9주차 과제 완료 - 김세안
  src/components/Comment/CommentElement.jsx
  src/components/Comment/index.jsx
  src/data/comments.js
  src/routes/PostDetailPage.jsx
Labels: LGTM

#58 9주차 과제제출
  package-lock.json
  package.json
  src/apis/api.js
  src/apis/axios.js
  src/assets/images/lion.jpeg
  src/components/Comment/CommentElement.jsx
  src/components/Comment/index.jsx
  src/components/Header/index.jsx
  src/components/Posts/index.jsx
  src/data/comment.js
  src/data/comments.js
  src/routes/HomePage.jsx
  src/routes/PostCreatePage.jsx
  src/routes/PostDetailPage.jsx
  src/routes/PostEditPage.jsx
  src/routes/SignInPage.jsx
  src/routes/SignUpPage.jsx
  src/utils/cookie.js
Labels: wontfix
